server.port=8000
services.logging-service[0].host=localhost
services.logging-service[0].port=8081
services.logging-service[1].host=localhost
services.logging-service[1].port=8082
services.logging-service[2].host=localhost
services.logging-service[2].port=8083

?services.messages-service[0].host=localhost
services.messages-service[0].port=8091
services.messages-service[1].host=localhost
services.messages-service[1].port=8092